version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Node.js dependencies...
      - cd app
      - npm install

  build:
    commands:
      - echo Building the app...
      - npm run build
      - cd ..
      - mkdir -p build-output
      - cp -r app/* build-output/

  post_build:
    commands:
      - echo Build complete!
      - zip -r app-artifact.zip build-output

artifacts:
  files:
    - app-artifact.zip
  discard-paths: yes

